pipeline:
  build:
    image: robbutcher2001/java8-tomcat8-docker
    commands:
      - cd butch-hello-world
      - mvn install
      - mv target/classes /tomcat/webapps/ROOT/WEB-INF
      - mv src/web.xml /tomcat/webapps/ROOT/WEB-INF
      - sh /tomcat/bin/catalina.sh run
